
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Adinda puspitasari
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        eJumlah.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ePlus = new javax.swing.JButton();
        eMinus = new javax.swing.JButton();
        eJumlah = new javax.swing.JTextField();
        eBeli = new javax.swing.JButton();
        eHapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelHarga = new javax.swing.JLabel();
        labelPesan = new javax.swing.JLabel();
        ePesanan = new javax.swing.JTextField();
        eHarga = new javax.swing.JTextField();
        labelJumlahPesanan = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        eJumlahPesanan = new javax.swing.JTextField();
        eTotal = new javax.swing.JTextField();
        rNasgor = new javax.swing.JRadioButton();
        rPecel = new javax.swing.JRadioButton();
        rGado = new javax.swing.JRadioButton();
        rGulai = new javax.swing.JRadioButton();
        rSoto = new javax.swing.JRadioButton();
        rMie = new javax.swing.JRadioButton();
        rSteak = new javax.swing.JRadioButton();
        rSate = new javax.swing.JRadioButton();
        rTom = new javax.swing.JRadioButton();
        rPasta = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WAROENG HISTORIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel1.setBackground(new java.awt.Color(187, 158, 215));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JUMLAH BELI");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INFORMASI PESANAN");

        ePlus.setText("+");
        ePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePlusActionPerformed(evt);
            }
        });

        eMinus.setText("-");
        eMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMinusActionPerformed(evt);
            }
        });

        eBeli.setText("BELI");
        eBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBeliActionPerformed(evt);
            }
        });

        eHapus.setText("HAPUS");
        eHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eHapusActionPerformed(evt);
            }
        });

        labelHarga.setText("Harga");

        labelPesan.setText("Pesanan Anda");

        labelJumlahPesanan.setText("Jumlah Pesanan");

        labelTotal.setText("Total");

        eJumlahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJumlahPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJumlahPesanan)
                            .addComponent(labelTotal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eJumlahPesanan)
                            .addComponent(eTotal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPesan)
                            .addComponent(labelHarga))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ePesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(eHarga))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal)
                            .addComponent(eTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPesan)
                            .addComponent(ePesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHarga)
                            .addComponent(eHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJumlahPesanan)
                            .addComponent(eJumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 44, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(eJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ePlus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(69, 69, 69))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(eBeli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eHapus)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ePlus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eMinus))
                    .addComponent(eJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eBeli)
                    .addComponent(eHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 250, 280));

        menu.add(rNasgor);
        rNasgor.setText("Nasi Goreng");
        getContentPane().add(rNasgor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        menu.add(rPecel);
        rPecel.setText("Pecel Lele");
        getContentPane().add(rPecel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        menu.add(rGado);
        rGado.setText("Gado-gado");
        getContentPane().add(rGado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        menu.add(rGulai);
        rGulai.setText("Gulai Ikan");
        getContentPane().add(rGulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        menu.add(rSoto);
        rSoto.setText("Soto Ayam");
        getContentPane().add(rSoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        menu.add(rMie);
        rMie.setText("Mie Goreng");
        getContentPane().add(rMie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        menu.add(rSteak);
        rSteak.setText("Steak Daging");
        getContentPane().add(rSteak, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        menu.add(rSate);
        rSate.setText("Sate Madura");
        getContentPane().add(rSate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        menu.add(rTom);
        rTom.setText("Tom Yum");
        getContentPane().add(rTom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        menu.add(rPasta);
        rPasta.setText("Pasta");
        getContentPane().add(rPasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eJumlahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJumlahPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eJumlahPesananActionPerformed

    private void eHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eHapusActionPerformed
        menu.clearSelection();
        eJumlah.setText("0");
        ePesanan.setText("");
        eJumlahPesanan.setText("");
        eTotal.setText("");
        eHarga.setText("");
    }//GEN-LAST:event_eHapusActionPerformed

    private void eBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBeliActionPerformed
        String pesanan = "";
        int harga = 0;
        boolean menuDipilih = false;

        if (rNasgor.isSelected()) {
            pesanan = "Nasi Goreng";
            harga = 12000;
            menuDipilih = true;
        } else if (rPecel.isSelected()) {
            pesanan = "Pecel Lele";
            harga = 15000;
            menuDipilih = true;
        }else if (rGado.isSelected()) {
            pesanan = "Gado-gado";
            harga = 10000;
            menuDipilih = true;
        }else if (rGulai.isSelected()) {
            pesanan = "Gulai Ikan";
            harga = 10000;
            menuDipilih = true;
        }else if (rSoto.isSelected()) {
            pesanan = "Soto Ayam";
            harga = 10000;
            menuDipilih = true;
        }else if (rMie.isSelected()) {
            pesanan = "Mie Goreng";
            harga = 12000;
            menuDipilih = true;
        }else if (rSteak.isSelected()) {
            pesanan = "Steak Daging";
            harga = 20000;
            menuDipilih = true;
        }else if (rSate.isSelected()) {
            pesanan = "Sate Madura";
            harga = 10000;
            menuDipilih = true;
        }else if (rTom.isSelected()) {
            pesanan = "Tom Yum";
            harga = 17000;
            menuDipilih = true;
        }else if (rPasta.isSelected()) {
            pesanan = "Pasta";
            harga = 15000;
            menuDipilih = true;

        }

       int jumlah = Integer.parseInt(eJumlah.getText());

    if (menuDipilih && jumlah > 0) {
        int totalHarga = harga * jumlah;
        ePesanan.setText(pesanan);
        eTotal.setText("Rp" + totalHarga);
        eHarga.setText("Rp" + Integer.toString(harga));
        eJumlahPesanan.setText(Integer.toString(jumlah));
    } else {
        JOptionPane.showMessageDialog(null, "Pilih menu dan pastikan jumlah beli lebih dari 0.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_eBeliActionPerformed

    private void eMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMinusActionPerformed
        int jumlah = Integer.parseInt(eJumlah.getText());
        jumlah--;
        eJumlah.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_eMinusActionPerformed

    private void ePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePlusActionPerformed
        int jumlah = Integer.parseInt(eJumlah.getText());
        jumlah++;
        eJumlah.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_ePlusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eBeli;
    private javax.swing.JButton eHapus;
    private javax.swing.JTextField eHarga;
    private javax.swing.JTextField eJumlah;
    private javax.swing.JTextField eJumlahPesanan;
    private javax.swing.JButton eMinus;
    private javax.swing.JTextField ePesanan;
    private javax.swing.JButton ePlus;
    private javax.swing.JTextField eTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelJumlahPesanan;
    private javax.swing.JLabel labelPesan;
    private javax.swing.JLabel labelTotal;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JRadioButton rGado;
    private javax.swing.JRadioButton rGulai;
    private javax.swing.JRadioButton rMie;
    private javax.swing.JRadioButton rNasgor;
    private javax.swing.JRadioButton rPasta;
    private javax.swing.JRadioButton rPecel;
    private javax.swing.JRadioButton rSate;
    private javax.swing.JRadioButton rSoto;
    private javax.swing.JRadioButton rSteak;
    private javax.swing.JRadioButton rTom;
    // End of variables declaration//GEN-END:variables
}
